language: perl
install: cpanm --notest YAML Test::Whitespaces Test::Warnings Time::HiRes Capture::Tiny Test::Differences
script: prove -l t xt/author xt
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
